import { Analytics } from '@vercel/analytics/react';

import './css/style.css'

import { Inter } from 'next/font/google'

import Header from '@/components/ui/header'
import Banner from '@/components/banner'
import Head from 'next/head';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <Head>
        <meta name="google-site-verification" content="luA1PTxwG2ELOY4tBYHyo4AveqbkNZQhMckUC8-_-m8" />
      </Head>
      <body className={`${inter.variable} scroll-smooth font-inter antialiased bg-white text-gray-900 tracking-tight`}>
        <div className="flex scroll-smooth flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          {children}
        </div>
        <Analytics />
      </body>
    </html>
  )
}
